### ISSUE TITLE
Timeout Control

### ISSUE THREAD

**Issue by wbraswell** [nferraz/perl-openai-api#1]
@nferraz Thanks for building this great Perl library!

You may not be surprised to learn that due to the unpredictable load on the public OpenAI servers, and thus their somewhat unreliable nature, we are seeing response times from less than 5 seconds up to 1 minute or more, for the same basic query.

We need some way to safely abandon requests after a certain period of time has passed, and gracefully fail so that the request can be made again if needed.

LWP::UserAgent has a timeout attribute, which I think is what we need to control this behavior:
https://metacpan.org/pod/LWP::UserAgent#timeout

If I'm reading the source correctly, this may be approximately where we need to insert some timeout-related code:
https://github.com/nferraz/perl-openai-api/blob/main/lib/OpenAI/API.pm#L63

Normally I would be happy to make a PR myself, but I have very little experience in this area so I am guessing it is better to follow your lead.

**Comment by nferraz** [comment]
Thanks for the suggestion!

Fixed on version 0.19.

**Comment by wbraswell** [comment]
@nferraz 
Wow that was fast, thanks!  I'll test it out and let you know how it works for me.
Meanwhile, I don't see the new "timeout" parameter mentioned anywhere in the documentation yet?
