### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by wbraswell** [nferraz/perl-openai-api#2]
Other than trial-and-error to avoid making too many requests in the first place, is there any way to gracefully fail (instead of dying) when this happens?

```Error retrieving 'completions': 429 Too Many Requests at /FOO/perl5/lib/perl5/OpenAI/API.pm line 48.```

$OpenAI::API::VERSION = 0.07

**Comment by kucharskim** [comment]
I think this is normal. I also get `429 Too Many Requests` when I send too many requests. Free tier always will have this problem. I'm not sure how to handle it better.

**Comment by William-Houser** [comment]
There are some suggestions here: https://platform.openai.com/docs/guides/rate-limits/error-mitigation

**Comment by nferraz** [comment]
Thank you all for the comments and feedback.

If you receive a `429 Too Many Requests`, that's an indication from the service to slow down (or increase your rate limit).

The request will be automatically retried in case of other (possibly recoverable) errors:

* 500 Internal Server Error
* 503 Service Unavailable
* 504 Gateway Timeout
* 599 Network Connect Timeout Error
