### ISSUE TITLE
There is a typo with version and CPAN shows 0.3 instead of 0.30

### ISSUE THREAD

**Issue by kucharskim** [nferraz/perl-openai-api#27]
Maybe because of this https://github.com/nferraz/perl-openai-api/commit/31cdf6198e3ee560ddb815abdc6bb8d17fb11de8#r105447995

**Comment by kucharskim** [comment]
I would bump it to 0.31 even if it a no-op. Current version(ing) is confusing on CPAN. Unless you are going to release new bump soon.

**Comment by nferraz** [comment]
I agree that it can be a bit confusing, but that's how CPAN works: 0.3 == 0.30 > 0.29 > 0.03

But, don't worry -- I'm going to release `0.31` soon. :)
