### ISSUE TITLE
Completions Endpoint Discontinued?

### ISSUE THREAD

**Issue by wbraswell** [nferraz/perl-openai-api#29]
As part of OpenAI's ending the Codex free demo, it seems that the completions() endpoint is also no longer working?
I get a 404 error when trying to call completions(), now I have to use the chat() endpoint only.

**Comment by nferraz** [comment]
Can you share a code example? My test is still working (using text-davinci-003):

```
OpenAI-API % perl -Ilib t/01-completions.t
ok 1
ok 2
ok 3
1..3
```

**Comment by wbraswell** [comment]
Dang I already updated all my code, so it will be a little tricky for me to get an example running quickly.
Let me ask you a question, if you use an invalid model name (not the valid model name 'text-davinci-003') for calling the completions() endpoint, then do you get a 404 error?

**Comment by nferraz** [comment]
Yes, the server will return a 404 for this kind of invalid request.

Perhaps I should return the entire error object instead, but that would be an backward incompatible change.

The advantage is that it could give more insight about the cause of the error.

**Comment by wbraswell** [comment]
Okay then it was probably just me using a now-invalid Codex model name which caused the 404 error, so I was presumably incorrect about completions() endpoint being discontinued.
It might be good to return the entire error object, if it contains more information.  I am happy to upgrade my code accordingly.
I guess you can close this issue if you like.
