### ISSUE TITLE
Timeout Control, Missing Moo Attributes & 400 Bad Request

### ISSUE THREAD

**Issue by wbraswell** [nferraz/perl-openai-api#3]
The new `timeout` parameter is never being properly set in the LWP::UserAgent object, because we did not yet create the corresponding Moo attributes in Completions.pm & friends.

Once I create the missing attributes and see that timeout is being properly set, I then immediately receive an error:
```Error retrieving 'completions': 400 Bad Request```

As soon as I remove the `timeout` from my OpenAI::API call, then it works properly again.  It even gives the same 400 error if I set the `timeout` to be equal to the default setting `180` which it is going to be whether or not I set it.  It also gives the same 400 error if we use the `LWP::UserAgent::timeout()` subroutine to set the timeout data.

$OpenAI::API::VERSION = 0.19
$LWP::UserAgent::VERSION = 6.68

**Comment by nferraz** [comment]
Thanks for spotting this issue!

I fixed the timeout, and implemented retries (with sleep between attempts) on version 0.21.
