### ISSUE TITLE
Please don't use AnyEvent.

### ISSUE THREAD

**Issue by karenetheridge** [nferraz/perl-openai-api#35]
See https://metacpan.org/pod/Perl::Critic::Policy::Community::DiscouragedModules#AnyEvent.

**Comment by nferraz** [comment]
Here's an attempt to replace AnyEvent with IO::Async::Loop: #39 

Would you like to review/comment before I merge it to main?

**Comment by nferraz** [comment]
One thing that I'm struggling with: I would like to make the module event-loop agnostic.

In other words, it should be possible to use it with AnyEvent, IO::Async or Mojo::IOLoop.

Let me know if you have any ideas!

**Comment by nferraz** [comment]
I think I have found a good solution:

```perl
    my $request = OpenAI::API::Request::Completion->new(
        model       => "text-davinci-003",
        prompt      => "Say this is a test",
        max_tokens  => 10,
        temperature => 0,
        config      => OpenAI::API::Config->new( event_loop_class => "IO::Async::Loop::Mojo" ),
    );
```

(The default will be "IO::Async::Loop".)
