### ISSUE TITLE
OpenAI test

### ISSUE THREAD

**Issue by steve2k2** [nferraz/perl-openai-api#42]
Hi - I installed the module and tried the test code (I set my API key in the %ENV).

I receive a too many Requests error.  Can you help me?  

Thank you,
steve@baselines.com

OPENAI
$VAR1 = bless( {
                 'config' => bless( {
                                      'retry' => 3,
                                      'timeout' => 60,
                                      'api_base' => 'https://api.openai.com/v1',
                                      'api_key' => 'KEY was available here',
                                      'sleep' => 1,
                                      'event_loop_class' => 'IO::Async::Loop'
                                    }, 'OpenAI::API::Config' )
               }, 'OpenAI::API' );
Error: '429 Too Many Requests'

**Comment by Ovid** [comment]
[This module is now deprecated](https://github.com/nferraz/perl-openai-api/pull/49) in favor of [OpenAPI::Client::OpenAI](https://metacpan.org/pod/OpenAPI::Client::OpenAI)

That module is a bit out of date, but I have a locally updated version I'll be creating a PR for soon.
