### ISSUE TITLE
error OpenAI::API::Request::Completion

### ISSUE THREAD

**Issue by marcontk** [nferraz/perl-openai-api#43]
Hi, I implemented a script based on the example in the documentation, the script works fine on MacOS Monterey Perl version 5.34.1. However on Linux Perl version 5.26.1 gives the following message:

Undef did not pass type constraint "Str" (in $args->{"api_key"}) at /usr/lib/perl5/site_perl/5.26.1/OpenAI/API/Request.pm line 17
    "Str" is a subtype of "Value"
    "Value" is a subtype of "Defined"
    Undef did not pass type constraint "Defined" (in $args->{"api_key"})
    "Defined" is defined as: (defined($_))

---- Script test ----

#!/usr/bin/perl

use OpenAI::API::Request::Completion;

while (){

        $myprompt = <STDIN>;

        my $completion = OpenAI::API::Request::Completion->new(

            model      => 'text-davinci-003',
            prompt     => $myprompt,
            max_tokens => 250,
        );

        my $myresponse  = $completion->send();
        my $resp = $myresponse->{choices}[0]{text};

        print "$resp\n\n";
}

---------

What could be the problem ?

**Comment by incognico** [comment]
Did you forget to supply the API-key?

**Comment by Ovid** [comment]
[This module is now deprecated](https://github.com/nferraz/perl-openai-api/pull/49) in favor of [OpenAPI::Client::OpenAI](https://metacpan.org/pod/OpenAPI::Client::OpenAI)

That module is a bit out of date, but I have a locally updated version I'll be creating a PR for soon.
