### ISSUE TITLE
Feature Request: Audio Transcription API

### ISSUE THREAD

**Issue by incognico** [nferraz/perl-openai-api#44]
Any plans to add createTranscription functionality? Would be nice to have.

https://platform.openai.com/docs/api-reference/audio/createTranscription

**Comment by incognico** [comment]
I have put something together for my usecase so if someone needs transcribing, feel free to use:

```perl
use v5.28.0;
use feature 'signatures';
no warnings 'experimental::signatures';
use LWP::UserAgent;
use File::Temp ':POSIX';
use Encode::Simple 'decode_utf8_lax';

sub transcribe($file) {
   say '** Transcribing...';

   if ($file =~ /\.aac$/) {
      my $newfile = tmpnam() . '.m4a';
      `ffmpeg -i $file -acodec copy $newfile >/dev/null 2>&1`; # API does not handle .aac, use ffmpeg to convert
      $file = $newfile;
   }

   my $ua = LWP::UserAgent->new;
   my $req = POST('https://api.openai.com/v1/audio/transcriptions',
      Content_Type => 'multipart/form-data',
      Authorization => 'Bearer ' . $ENV{'OPENAI_API_KEY'},
      Content => [
         file => [$file],
         model => 'whisper-1',
         response_format => 'text',
      ],
   );

   my $res = $ua->request($req);
   if ($res->is_success) {
      my $m = decode_utf8_lax($res->content);
      chomp($m);
      say $m;
   else {
      say '** Error Transcribing: ' . $res->status_line;
   }
   unlink $file;
}
```

**Comment by trbutler** [comment]
I've been working on something similar. I just submitted a pull request that implements OpenAI::API::Request::Audio. Here's the request: https://github.com/nferraz/perl-openai-api/pull/45

**Comment by Ovid** [comment]
[This module is now deprecated](https://github.com/nferraz/perl-openai-api/pull/49) in favor of [OpenAPI::Client::OpenAI](https://metacpan.org/pod/OpenAPI::Client::OpenAI)

That module is a bit out of date, but I have a locally updated version I'll be creating a PR for soon.
